---
# Playbook to create webserver
- hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes

    - name: Provision Git
      apt:
        name:
              - git

    - name: Install Java
      shell: |
        apt install openjdk-17-jdk-headless --yes

    - name: Install .NetCore, ASP.NetCore
      shell: |
        apt install dotnet-sdk-7.0 --yes
        apt install aspnetcore-runtime-7.0 --yes
        apt install dotnet-runtime-7.0 --yes
        apt-get install lynx --yes

    - name: Install VSCode
      shell: |
        apt update -y
        apt upgrade -y
        apt install software-properties-common apt-transport-https wget apt-utils --yes
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -
        add-apt-repository --yes "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        apt install code -y
        echo 'Installed'
        
        

    - name: Install Maven using Ansible
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - maven

    - name: Install PostgreSQL
      shell: |
        sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
        apt-get update -y
        apt-get -y install postgresql
    #Check its version with "psql --version"



