---
# Playbook to create webserver
- hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes

    - name: Provision Git
      apt:
        name:
              - git

    - name: Install Java
      shell: |
        apt install openjdk-17-jdk-headless --yes

    - name: Install .NetCore, ASP.NetCore
      shell: |
        apt install dotnet-sdk-7.0 --yes
        apt install aspnetcore-runtime-7.0 --yes
        apt install dotnet-runtime-7.0 --yes
        apt-get install lynx --yes


    # - name: Provision other packages for .NetCore apps
    #   shell: |
    #     # apt-get update -y && apt-get install -yqq daemonize dbus-user-session fontconfig
    #     # daemonize /usr/bin/unshare --fork --pid --mount-proc /lib/systemd/systemd --system-unit=basic.target exec nsenter -t $(pidof systemd) -a su - $LOGNAME
    #     # apt install wget -y
    #     # wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    #     # dpkg -i packages-microsoft-prod.deb
    #     apt update -y
    #     apt install apt-transport-https -y
    #     apt update -y
    #     apt install dotnet-sdk-6.0
    # - name: Provision the rest of packages properly for .NetCore apps
    #   apt:
    #     name:
    #           - dotnet-runtime-6.0
    #           - aspnetcore-runtime-6.0

    - name: Install VSCode
      shell: |
        apt install software-properties-common apt-transport-https wget --yes
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -
        add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" --yes
        apt install code --yes

    - name: Install Maven using Ansible
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - maven


    - name: Install PostgreSQL
      shell: |
        sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
        apt-get update -y
        apt-get -y install postgresql
    #Check its version with "psql --version"

    - name: Install Apache
      apt:
        name: apache2
        state: latest
    # - name: Creating folder for files.
    #   file:
    #     path: /home/ubuntu/htmll/
    #     state: directory
    #     owner: root
    #     group: root
    #     mode: '0755'

    - name: Copy index.html template to Apache configuration
      copy:
        src: ../../../Frontend/index.apache-debian.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'

    - name: Create build directory
      file:
        path: /root/app_stack
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: /home/runner/app_content
        dest: /root/demo-lamp_stack/
        owner: root
        group: root
        mode: '0644'
        
    - name: Docker images
      shell: docker images

    - name: Build and push container image
      community.docker.docker_image:
        build:
          path: /root/demo-lamp_stack/app_content_content/
        name: dock1998/lamp_stack_new:v1
        source: build
        state: present
    - name: Running the container
      community.docker.docker_container:
        image: dock1998/lamp_stack_new:v1
        name: lamp_stack_new_cont
        state: started
        ports: "8080:80"
    - name: Tag and push to docker hub
      community.docker.docker_image:
        name: dock1998/lamp_stack_new:v1
        repository: dock1998/lamp_stack_new:v2
        push: yes
        source: local
        state: present
    # - name: Restarting service Apache, in all cases
    #   ansible.builtin.service:
    #     name: apache2
    #     state: restarted

    # - name: Install Apache2
    #   shell: |
    #     apt-get install apache2 -y
    #     apt install snapd -y
    #     snap install dotnet-sdk


