---
# Playbook to deploy the app
- hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
    - name: Hello world
      shell: |
        touch /root/$ANSIBLE_PASSWORD
        touch /root/$OTHER_PASSWORD
    - name: a
