---
# Playbook to build and push the image
- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: build and push container image
      community.docker.docker_image:
        build:
          path: /root/demo-lamp_stack/LAMP_STACK_content/
        name: dock1998/lamp_stack_new:v1
        source: build
        state: present
    - name: Running the container
      community.docker.docker_container:
        image: dock1998/lamp_stack_new:v1
        name: lamp_stack_new_cont
        state: started
        ports: "8080:80"



                 # sudo docker build --no-cache -t test-app /home/runner/app_content/.