name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo $HOME
          ls /home/runner/work
          apt install ansible -y
          ansible --version