name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3        

      - run: |
          sudo apt install tree -y
          sudo mkdir /home/runner/app_content
          sudo chmod 755 /home/runner/app_content
          echo '1st ls'
          sudo ls /var/www/html/
          sudo rm -f /var/www/html/index.html
          echo '2nd ls'
          sudo ls /var/www/html/
          echo ''
          sudo ls /home/runner/work/DevOps-Interview-AC/DevOps-Interview-AC/Infrastructure/conf_mgmt_ansible/Infrastructure/conf_mgmt_ansible/

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
