name: CI
on: [workflow_dispatch]
jobs:
  docker-install-and-preliminar-config:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3        

      - run: |
          sudo apt update -y
          sudo mkdir /home/runner/app_content
          sudo chmod 755 /home/runner/app_content
          echo ''
          sudo ls /home/runner/

        
