name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        run: |
          mkdir -p $HOME/app
          chmod 755 $HOME/app
      - uses: actions/checkout@v3
        with:
          path: '$HOME/app'
      - name: Run a multi-line script
        run: |
          echo $HOME
          ls $HOME/app