name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        run: |
          sudo su
          mkdir -p /srv/app
          chmod 755 /srv/app
          exit
      - uses: actions/checkout@v3
        with:
          path: '/srv/app'
      - name: Run a multi-line script
        run: |
          echo Hello,
          echo there.