name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3        

      - run: |
          sudo apt update -y
          sudo apt install tree -y
          sudo mkdir /home/runner/app_content
          sudo chmod 755 /home/runner/app_content
          sudo rm -f /var/www/html/index.html
          echo ''
          sudo cp /home/runner/work/DevOps-Interview-AC/DevOps-Interview-AC/Infrastructure/conf_mgmt_ansible/Dockerfile /home/runner/app_content/Dockerfile
          sudo ls /home/runner/app_content/
          #Install ansible
          sudo apt install ansible -y
          sudo ls /home/runner/work/DevOps-Interview-AC/DevOps-Interview-AC/Infrastructure/conf_mgmt_ansible/playbooks
          sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" -y
          apt-cache policy docker-ce
          sudo apt install docker-ce -y
          sudo ansible-playbook /home/runner/work/DevOps-Interview-AC/DevOps-Interview-AC/Infrastructure/conf_mgmt_ansible/playbooks/01-image-build-and-push.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
