name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3

      - name: Run a multi-line script
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          sudo su
          cd /home/runner/work/
          apt install tree -y
          tree
          ls /home/runner/work
