name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3        

      - run: |
          sudo cd /home/runner/work/
          sudo apt install tree -y
          tree
          sudo ls /home/runner/work
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
