name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        run: |
          mkdir -p /home/runner/app
          chmod 755 /home/runner/app
      - uses: actions/checkout@v3
        with:
          path: '/home/runner/app'
      - name: Run a multi-line script
        run: |
          echo $HOME
          ls /home/runner/app