name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3        

      - run: |
          cd /home/runner/work/
          apt install tree -y
          tree
          ls /home/runner/work
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
