name: CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo cd /home/runner/work/
          sudo apt install tree -y
          tree
          ls /home/runner/work
