name: CICD
on: [workflow_dispatch]
jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3 

      - run: |
          sudo apt update -y
          sudo mkdir /home/runner/app_content
          sudo chmod 755 /home/runner/app_content
          echo ''
          sudo cp ./Dockerfile /home/runner/app_content/Dockerfile
          sudo ls /home/runner/app_content/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: vitr/actions-build-and-upload-to-ecs@master      
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: main-applications-registry
          region: us-east-1
          tags: latest,${{ github.sha }}
          create_repo: true
      - run: |
          ls /home/runner/
          echo 'Hey'
          sudo docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-20.04  
    steps:
      - name: Clone test-app repo
        uses: actions/checkout@v3   

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - run: |
          sudo apt update -y
          sudo apt install ansible -y
          sudo apt install tree -y
          sudo tree /home/runner/DevOps-Interview-AC/          
          ansible-playbook /home/runner/work/DevOps-Interview-AC/DevOps-Interview-AC/Infrastructure/conf_mgmt_ansible/playbooks/02-image-pull-and-deploy.yml
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 729158664723.dkr.ecr.us-east-1.amazonaws.com
          sudo docker run -d -p 80:80 --name main-applications-registry 729158664723.dkr.ecr.us-east-1.amazonaws.com/main-applications-registry
          sudo docker ps
          echo 'Done'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ssh export asdasda ec2
  # ssh user1@server1 'command2'
  # ssh -i "candidate.pem" ubuntu@44.212.23.136 'export TEST="ItsASecret"  | command2'


  # export AWS_ACCOUNT_ID=$(aws secretsmanager get-secret-value --secret-id app/AWS_ACCOUNT_ID | jq -r .SecretString)
  # sudo ls /home/runner/work/DevOps-Interview-AC/DevOps-Interview-AC/Infrastructure/conf_mgmt_ansible/playbooks
  # aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
  # sudo docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/main-applications-registry:latest
  # sudo docker images
  # sudo docker run -d -p 80:80 --name main-applications-registry ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/main-applications-registry
  # curl localhost:80
        


      


  # ssh COMANDO (docker build ${{ secrets.GITHUB_TOKEN }} )   a maquina ec2
        
